### ISSUE TITLE
set up initial project structure

### ISSUE THREAD

**Issue by mgenov** [clouway-incubator/bankapp#1]
Initial project of the structure need to be created. Need to be considered how GOPATH will be handled and how Backend app will be build. 

Here is a sample structure that could be taken as starting point:
```
bankapp
   frontend
   cmd/bankapp/main.go
   bank/
```

**Comment by iliyanmotovski** [comment]
Can I have a hint about the structure of the Backend?

**Comment by mgenov** [comment]
It's already in the body of the issue: 

bank/ will hold app wide packages 
cmd/bankapp/main.go will be entry point of the application 

It's following the same structure as in: 
https://talks.golang.org/2014/organizeio.slide#9

**Comment by IvelinYR** [comment]
Can I understand that now we only have to set up project structure.
### Example:

actions/
      _CommandActions.js
      UserActions.js_

components/
      _Header.js
      Sidebar.js

Command.js
      CommandList.js
      CommandItem.js
      CommandHelper.js
      User.js
      UserProfile.js
      UserAvatar.js
_
containers/
      _App.js
      Command.js
      User.js_

reducers/
      _index.js
      command.js
      user.js_

routes.js

**Comment by mgenov** [comment]
The frontend app should be placed in the frontend folder as it was shown in the body of the issue. 

frontend/src
frontend/build

npm run build -> builds app into frontend/build and this app need to be served by the Go App. 


in the root folder of the project there maybe a build.sh script which to:
```bash
#!/bin/bash

cd frontend
npm run build 
cd ..
mkdir -p static
cp -fr frontend/build/* static/* 
```

Where the Go application (cmd/bankapp/main.go) should serve the static files with: 
```golang
http.FileServer(http.Dir("static")
```

Keep in mind that static folder should be added to .gitignore and should not be committed.

**Comment by mgenov** [comment]
I've added few tips for structuring of the frontend using Redux Ducks (modules) in: https://github.com/clouway/teamspace/wiki/Building-Web-Apps-Using-React 

Example:
```
src/components/ - (presentational components)
src/containers/ - (AccountsContainer.js) 
src/redux/modules/ - (accounts.js, users.js, operations.js)
src/store -> createStore, middlewares and etc
```

The structure looks reasonable for mid and large sized projects.

**Comment by mgenov** [comment]
Added in #12 and #8 with some of the functionalities.
